version: '3'
services:
  frontend:
    image: saahils171/forum-client:latest
    ports:
      - "3000:3000"
    restart: always

  backend:
    image: saahils171/forum-server:latest
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env   
    restart: always

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
